### ISSUE TITLE
The dimension of the output of Wordembedding using GloVe50D is not right

### ISSUE THREAD

**Issue by Stephen0620** [microsoft/NimbusML#154]
**Describe the bug**
The dimension of the output of Wordembedding using GloVe50D is not right

**To Reproduce**
1. Run following code
```python
from nimbusml import Pipeline
from nimbusml.feature_extraction.text.extractor import Ngram
from nimbusml.feature_extraction.text import NGramFeaturizer
from nimbusml.feature_extraction.text import WordEmbedding
from nimbusml.preprocessing.schema import ColumnSelector
import pandas as pd

data = {'Expression': [
                       'tops',
                       'tip',
                       'top'
                       ]}

df = pd.DataFrame(data)
print(df)

pipe = Pipeline([
                NGramFeaturizer(word_feature_extractor=Ngram(),
                                columns={'ngram': 'Expression'},
                                output_tokens_column_name='Expression_Transform'),
                WordEmbedding(model_kind='GloVe50D', columns={'Feature': 'Expression_Transform'}),
                ColumnSelector(columns=['Feature'])
        ])

feature = pipe.fit_transform(df)
print(feature)
```

**Expected behavior**
The output should have only 50 dimensions, instead, got 150
Note: 
The first 50 numbers are the same as the second and the last 50 numbers

**Comment by justinormont** [comment]
The Word Embedding transform outputs the min/avg/max of the word embeddings for the tokens in the string. This produces the average which is likely the output you're expecting along with the bounding hyper-rectangle of the tokens in the word embedding space.

More info:
* https://github.com/dotnet/machinelearning/blob/fc89745fd9d5d7dcca875570bd3b9ffc981f2184/docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Text/ApplyWordEmbedding.cs#L24-L30
* https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.staticpipe.wordembeddingsstaticextensions.wordembeddings?view=ml-dotnet-preview

For why they are equal, when operating on single word/token strings, the min/average/max will all match. If you feed in longer strings, they should no longer be equal.

**Comment by Stephen0620** [comment]
Thanks for replying. It makes total sense now.
