### ISSUE TITLE
Dense features in NimbusML

### ISSUE THREAD

**Issue by alexleech** [microsoft/NimbusML#177]
| FeatureA |      FeatureB      |  Label |
|:----------|:-------------:|:------:|
| [1, 2, 3, 4] |  0.1 | 1 |
| [5, 6, 7, 8] |    0.2   |   0 |

Say FeatureA is an array, under the current API, it seems unfeasible to consume this data schema in a tree algorithm. I understand it's doable to expand FeatureA into FeatureA1 to FeatureA4 with which contains only one scalar. However, in C# runtime code, it would end up with low readability since we would need to create a class containing multiple member variables for the model trained by NimbusML. 
For example:
```
public class MyFeatures
{
    public double FeatureA1 { get; set; }
    public double FeatureA2 { get; set; }
    public double FeatureA3 { get; set; }
    public double FeatureA4 { get; set; }
    public double FeatureB { get; set; }
}
```
Instead of:
```
public class MyFeatures
{
    [VectorType(4)]
    public double[] FeatureA { get; set; }
    public double FeatureB { get; set; }
}
```
Please correct me if I'm wrong. Thanks!

**Comment by ganik** [comment]
>> under the current API, it seems unfeasible to consume this data schema in a tree algorithm
Its possible to define schema like that in NimbusML. You would need to use fdata = FileDataStream.read_csv() and then inspect / fix the fdata.schema to define vector of nums on first 4 fields. Then just follow examples on using FileDataStream (https://www.youtube.com/watch?v=eaNoDLs-S7Y&t=670s)
