### ISSUE TITLE
Exposing this feature through nimbus: Combining 2 model into single model

### ISSUE THREAD

**Issue by vinodshanbhag** [microsoft/NimbusML#178]
Currently automl service builds a training pipeline by first doing featurization and then doing final training. Hence it ends up with 2 models (2 zips).  Final model that is delivered to customers should be a single model (assuming better perf/maintainability etc).  Hence we need a nimbus wrapper so we can combine these 2 models into one.

**Comment by justinormont** [comment]
Having two separate models, one for featurization and one for the trainer can be difficult to do correctly.

For instance, in CV mode we have to ensure that a new featurization model is created for each of the CV folds, or alternatively that none of the featurizers are stateful (text, categorical, term/tokey, etc transform).
