### ISSUE TITLE
Passing in an explicit evaltype to a NimbusML pipeline causes errors.

### ISSUE THREAD

**Issue by pieths** [microsoft/NimbusML#193]
Passing in an explicit `evaltype` to a NimbusML `Pipeline` when predicting, testing or scoring causes errors. This is required when using a pipeline that was loaded from disk with `load_model`.

In the `Pipeline._predict()` method, if the `y` argument is defined, a call to `_evaluation_infer()` is made. In `_evaluation_infer()`, if `evaltype` is `auto` then certain nodes are added to the node list. If `evaltype` is not `auto` then control is passed to `_evaluation()` to add nodes to the list. `_evaluation_infer()` and `_evaluation()` do not do the same thing for the following types:

- __cluster__ (verified to cause error; see below)
- __anomaly__ (potentially an error; unverified)
- __ranking__ (potentially an error; unverified)

Here is an example that produces the error.

```python
import pandas
from nimbusml import Pipeline
from nimbusml.cluster import KMeansPlusPlus

# define 3 clusters with centroids (1,1,1), (11,11,11) and (-11,-11,-11)
X_train = pandas.DataFrame(data=dict(
    x=[0, 1, 2, 10, 11, 12, -10, -11, -12],
    y=[0, 1, 2, 10, 11, 12, -10, -11, -12],
    z=[0, 1, 2, 10, 11, 12, -10, -11, -12]))

# these should clearly belong to just 1 of the 3 clusters
X_test = pandas.DataFrame(data=dict(
    x=[-1, 3, 9, 13, -13, -20],
    y=[-1, 3, 9, 13, -13, -20],
    z=[-1, 3, 9, 13, -13, -20]))

y_test = pandas.DataFrame(data=dict(
    clusterid=[2, 2, 1, 1, 0, 0]))

pipe = Pipeline([
    KMeansPlusPlus(n_clusters=3)
]).fit(X_train)

metrics, predictions = pipe.test(X_test, y_test, output_scores=True, evaltype="cluster")
```

Produces this error:

```console
Error: *** System.ArgumentOutOfRangeException: 'Schema mismatch for label column 'clusterid': expected Single or Key, got Int64
```

If the `evaltype` argument is removed from the `test()` call above then everything works as expected.

**Comment by geoffery66** [comment]
I am still getting the same error even though I am excluding the "evaltype" argument.
I have also follow the official documentation to change dtype with:
`schema = DataSchema.read_schema('data.txt', collapse=True, sep=',',
                                dtype={'column_name': np.float32})

Error: *** System.ArgumentOutOfRangeException: 'Schema mismatch for input column 'column_name': expected Single, got Int64
Parameter name: inputSchema'

**Comment by pieths** [comment]
This should be fixed by [commit](https://github.com/microsoft/NimbusML/commit/1f97c9ef55f5e257f989db5f375cca5c55880258).
