### ISSUE TITLE
Model summary for trees

### ISSUE THREAD

**Issue by ganik** [microsoft/NimbusML#217]
Currently model summary for trees in ML.NET  returns vectorized output. 
* Need to double check it doesnt break NimbusML
* If it does, needs a fix either in ML.NET or NimbusML

**Comment by pieths** [comment]
The following three tree based predictors throw an error when retrieving the summary after a `fit()`.

- FastTreesBinaryClassifier
- FastTreesRegressor
- FastTreesTweedieRegressor
- FastForestBinaryClassifier
- FastForestRegressor

Here is the error output. Note, the second error only shows up after the `CategoricalSplitFeatures` column has been dropped.

> Error: *** System.NotSupportedException: 'Column has variable length vector: CategoricalSplitFeatures.
> Not supported in python. Drop column before sending to Python

> Error: *** System.NotSupportedException: 'Column has variable length vector: CategoricalCategoricalSplitFeatureRange.
> Not supported in python. Drop column before sending to Python

It looks like the IDataView summary output for all the tree based predictors gets created in `src\Microsoft.ML.FastTree\Utils\RegressionTreeBaseUtils.cs` in ml.net.

**Comment by pieths** [comment]
Three of the LightGbm predictors are effected by this as well.

- LightGbmBinaryClassifier
- LightGbmRanker
- LightGbmRegressor

**Comment by pieths** [comment]
The summaries now work as expected because variable column support was added in commit df1cf21507cc261ca43339e271919f89ee7537c5.
