### ISSUE TITLE
Documentation for scoring model in ML.NET is out of date

### ISSUE THREAD

**Issue by ganik** [microsoft/NimbusML#275]
There is no Legacy.LearningPipeline anymore in ML.NET so the doc below needs to be updated 
https://docs.microsoft.com/en-us/nimbusml/loadsavemodels#scoring-in-mlnet

**Comment by mstfbl** [comment]
Hello, I'm going to make the change on the website, but I can't locate the file to edit.

This file exists: https://github.com/microsoft/NimbusML/blob/master/src/python/docs/sphinx/loadsavemodels.rst

But this file does not have the code for "load_save_model.cs". It just says "load_save_model_csharp to be inserted." The website (https://docs.microsoft.com/en-us/nimbusml/loadsavemodels) also does not have an edit option. Do you know how I can make changes to this? Thanks!

**Comment by najeeb-kazmi** [comment]
Preview can be viewed here. Will merge to live docs once I've updated the docs for the 1.5 release.

https://review.docs.microsoft.com/en-us/nimbusml/overview?view=nimbusml-py-latest&branch=smoke-test
