### ISSUE TITLE
CharTokenizer example throws System.Runtime.InteropServices.SEHException

### ISSUE THREAD

**Issue by montebhoover** [microsoft/NimbusML#31]
https://github.com/Microsoft/NimbusML/blob/master/src/python/nimbusml/examples/CharTokenizer.py was noted for for throwing execption when called with `CharTokenizer(columns={'id_1': 'id', 'edu_1': 'education'})`:

```Error: *** System.Runtime.InteropServices.SEHException: 'External component has thrown an exception.'```

First noted by GalOshri in March 2018 - needs confirmation that this still repros and/or fix.

**Comment by Stephen0620** [comment]
Please check `#153`
