### ISSUE TITLE
Idea: Separate out dotnet into its own package

### ISSUE THREAD

**Issue by ganik** [Microsoft/NimbusML#4]
A large part of the NimbusML package now is the dotnet runtime. This means that on every update, users of NimbusML will have to download the dotnet runtime again, which probably won't change as fast as NimbusML itself. This seems wasteful to me.

Can we instead move the dotnet runtime into its own PyPI package that NimbusML depends on? That way, users only have to download NimbusML whenever there is an update.

**Comment by dhirschfeld** [comment]
pip doesn't really work with non-python dependencies but this would work very well with conda imho

**Comment by ganik** [comment]
Thank you Dave, there is a python package recently released that contains dotnetcore2 bits: https://pypi.org/project/dotnetcore2/  Ideally we would use it as a dependency
