### ISSUE TITLE
No distribution found

### ISSUE THREAD

**Issue by pmasl** [microsoft/NimbusML#458]
Python 3.8 installed, when trying to install nimbusml get an error stating it's not found

C:\Users\MyUser>python -m pip install nimbusml
ERROR: Could not find a version that satisfies the requirement nimbusml (from versions: none)
ERROR: No matching distribution found for nimbusml

**Comment by ganik** [comment]
@pmasl  we havent released python 3.8 distribution yet. Its on our plate, ETA couple months.

**Comment by pmasl** [comment]
Thank you
