### ISSUE TITLE
Extraneous xref in documentation links  

### ISSUE THREAD

**Issue by justinormont** [microsoft/NimbusML#47]
Documentation links in the [API Guide](https://docs.microsoft.com/en-us/nimbusml/apiguide?view=nimbusml-py-latest#binary-classifiers) need to point to the actual pages. Perhaps the xref paths are not found by the documentation render causing it to leave the original in place?

Currently some links retain an extraneous xref:
```html
<a href="xref:nimbusml.linear_model.AveragedPerceptronBinaryClassifier">...</a>
````

When the final rendered link should be: 
```html
<a href="../python/api/nimbusml/nimbusml.linear_model.AveragedPerceptronBinaryClassifier">...</a>
```

https://docs.microsoft.com/en-us/nimbusml/apiguide?view=nimbusml-py-latest#binary-classifiers

**Comment by justinormont** [comment]
Thanks for checking on this.

Links are now correctly handled.
 
Was: 
```html
<a href="xref:nimbusml.linear_model.AveragedPerceptronBinaryClassifier">...</a>
```
 
Now: 
```html
<a class="xref" href="https://docs.microsoft.com/python/api/nimbusml/nimbusml.linear_model.averagedperceptronbinaryclassifier" data-linktype="external">...</a>
```

**Comment by najeeb-kazmi** [comment]
Links are rendering correctly now, without a change on NimbusML side.
