### ISSUE TITLE
TLS Links for Improved Security

### ISSUE THREAD

**Issue by justinormont** [microsoft/NimbusML#57]
For general web security, we should use HTTPS links instead of HTTP.

Within the ML.NET repo, I see ~76 locations where we use HTTP:
https://github.com/Microsoft/NimbusML/search?p=3&q=http%3A%2F%2F&unscoped_q=http%3A%2F%2F

Task:
* Verify that HTTPS links are equivalent
* Where possible, change links to utilize HTTPS

Issue #52 / PR #56 handles this for scikit-learn, this is a more general task.

**Comment by skasturi** [comment]
Quick PR for this: https://github.com/Microsoft/NimbusML/pull/98
