### ISSUE TITLE
Identify all NimbusML components that rely on entrypoints in the ML.NET Legacy namespace.

### ISSUE THREAD

**Issue by montebhoover** [Microsoft/NimbusML#64]
As noted in https://github.com/dotnet/machinelearning/issues/1565, there are some ML.NET entrypoints required by NimbusML that are part of the Legacy namespace that will need to be migrated.   Take ModelCombiner for example: 

> https://github.com/dotnet/machinelearning/blob/7b2461cfdad150047dbbcbc163290a32e9f4d829/src/Microsoft.ML.Legacy/Runtime/EntryPoints/ModelOperations.cs#L81
> 
> As it is an entry-point, it was [duly published in NimbusML as we see here](https://github.com/Microsoft/NimbusML/blob/e1004720ec0c252ba87f02c190c33739d9c00f20/src/python/nimbusml/internal/entrypoints/models_ovamodelcombiner.py), and this internal entry-point definition actually [wound up being used here](https://github.com/Microsoft/NimbusML/blob/e1004720ec0c252ba87f02c190c33739d9c00f20/src/python/nimbusml/model_selection/cv.py#L474).

We need to identify which NimbusML components rely on entrypoints in the ML.NET Legacy namespace so we can make a plan for migrating them.

**Comment by justinormont** [comment]
@srsaggam: We should watch this issue as the entrypoints seems to be in flux. 

@montebhoover: Background... the AutoML system in ML.NET currently thinks using the entrypoint APIs, so this may have impact on the project too.

**Comment by montebhoover** [comment]
Thanks Justin.  I'll prioritize this so ML.NET has a list of entrypoints that need to be migrated and we can make sure nothing slips through unintentionally.

**Comment by montebhoover** [comment]
Updated list here: https://github.com/dotnet/machinelearning/issues/1565#issuecomment-445987962
