### ISSUE TITLE
How do you inspect the JSON entry point graph that NimbusML sends to ML.NET?

### ISSUE THREAD

**Issue by montebhoover** [Microsoft/NimbusML#74]
This comes out of a discussion @srsaggam were having:

When you call .fit() on any pipeline, NimbusML creates a JSON representation of the pipeline and sends it to the ML.NET entry point API.  Here are steps to inspect that JSON graph and to execute arbitrary graphs in ML.NET:
1. When you call .fit(), NimbusML creates the JSON graph [here in the src](https://github.com/Microsoft/NimbusML/blob/e1004720ec0c252ba87f02c190c33739d9c00f20/src/python/nimbusml/pipeline.py#L1108).
2. The following lines will print out the JSON graph and the name of your data file:
```
graph_info = pipeline._fit_graph(train_data, None, True)
graph = graph_info[0]
file = graph_info[1]
print(graph)
print(file.filename)
```
3. You can run this or any arbritrary entrypoint graph with [this unit test in ML.NET](https://github.com/dotnet/machinelearning/blob/9db16c85888e7163c671543faee6ba1f47015d68/test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs#L606)
    1. It's possible to copy and paste your own JSON in place of the JSON in the unit test, but it is probably simpler to just paste your JSON to a file and reference your file in the unit test as follows:
```
var args = new ExecuteGraphCommand.Arguments() { GraphPath = @"C:\Users\monte\Downloads\temp2\sample_graph.txt"};
var cmd = new ExecuteGraphCommand(Env, args);
cmd.Run();
```
4. There are three modifications you must make to the JSON you see from `print(graph)`:
    1. Add the file for your data set under `"inputs": { "file":`.
    2. Add a path to output a model file under `"outputs": { "output_model":`.
    3. Change `"inputs":`, `"nodes":` and `"outputs":` to `"Inputs":`, `"Nodes":` and `"Outputs":`. (Yes, I'm sorry but this is necessary...)
5. Here is an example of a JSON that will execute properly (if you set the filepath references in it to point to your local system): [sample_graph.txt](https://github.com/Microsoft/NimbusML/files/2688031/sample_graph.txt)

@Microsoft/pymlnet @glebuk @yaeldekel @justinormont Is this the recommended way of inspecting and running an entry point graph?  Let me know if there are better methods for this.

**Comment by srsaggam** [comment]
I have a question here : I believe that there is a call to entrypoint in ML.NET while we do Predict. How do we get the outgoing Json printed for that. I understand that _fit_graph works for the Fit() but is there anything similar for Predict() ?

**Comment by abgoswam** [comment]
@montebhoover .  Previously NimbusML  would dump out the entire graph whenever it would hit an exception. Is that still the case ?   

If yes, then perhaps  we can have a *hacky* solution to view the graph  in Pipeline.predict()  by somehow passing arguments to predict()  that will raise [this](https://github.com/Microsoft/NimbusML/blob/f3eb0bb364912e8e3812bbeece069d57a30033cc/src/python/nimbusml/pipeline.py#L1789) exception ?

**Comment by srsaggam** [comment]
Right now I have changed the file directly in my conda env to print the graph to Jupyter Notebook. I have put print(graph) after [this](https://github.com/Microsoft/NimbusML/blob/f3eb0bb364912e8e3812bbeece069d57a30033cc/src/python/nimbusml/pipeline.py#L1771) line.
