### ISSUE TITLE
How do we deal with ML.NET API change for ColumnSelector/ColumnDropper?

### ISSUE THREAD

**Issue by montebhoover** [Microsoft/NimbusML#76]
In ML.NET 0.7 there was a breaking change in the [entrypoint API for ColumnSelector and ColumnDropper](https://github.com/dotnet/machinelearning/blob/9db16c85888e7163c671543faee6ba1f47015d68/src/Microsoft.ML.Data/EntryPoints/SchemaManipulation.cs#L28) - they were merged into one single entrypoint that takes different parameters:

Before:
ColumnSelector(columns) 
ColumnDropper(columns)

After:
ColumnSelector(keep_columns, drop_columns)

There's a two different ways we can update to this:
1. Change the entry point signature in ML.NET to wrap the new code but expose an identical API as before.
2. Change existing NimbusML source and examples to conform to the new entry point signature.  If we do this there is a small side effect:
    - These are both of type `Transform` and all transforms except for this new signature accept a parameter named `columns`.  If we remove that expected named parameter, our `<<` syntax will no longer work for this component.

I recommend going with Option 2 in order to maintain similarity with ML.NET versus maintaining backward compatibility with earlier NimbusML releases.  Any thoughts? @glebuk @ganik @singlis @shmoradims

**Comment by glebuk** [comment]
My suggestion is not to modify ML.NET AND not to break backwards compatibility for NimbusML:

- Keep  existing ColumnSelector, add optional parameter to drop columns
- Keep the existing ColumnDropper() but mark it as deprecated. Make it call ColumnSelector under the hood
- remove ColumnDropper in a few versions.

**Comment by montebhoover** [comment]
I like the way you have implemented this Gani.  I'll add my review to the PR.  Thanks!
