### ISSUE TITLE
DotNetBridge: Refactor IRowCursor to RowCursor

### ISSUE THREAD

**Issue by montebhoover** [Microsoft/NimbusML#82]
[`IRowCursor`](https://github.com/Microsoft/NimbusML/blob/80ce48f0505eba1564dafd2dfd249905ee7b6143/src/DotNetBridge/NativeDataView.cs#L221)
Change from `IRowCursor` to `RowCursor`.

**Comment by shmoradims** [comment]
Fixed by #77.
