### ISSUE TITLE
DotNetBridge: Implement IHostEnvironment

### ISSUE THREAD

**Issue by montebhoover** [Microsoft/NimbusML#83]
[`HostEnvironmentBase`](https://github.com/Microsoft/NimbusML/blob/e1004720ec0c252ba87f02c190c33739d9c00f20/src/DotNetBridge/RmlEnvironment.cs#L13)
Instead of inheriting from ML.NET's HostEnvironmentBase, NimbusML should implement it's own [`IHostEnvironment`](https://github.com/dotnet/machinelearning/blob/0c62e30b4d9eabb60322b2a3e75bc90e20007889/src/Microsoft.ML.Core/Data/IHostEnvironment.cs#L31).

**Comment by montebhoover** [comment]
We need to implement some way of registering assemblies: https://github.com/Microsoft/NimbusML/blob/e1004720ec0c252ba87f02c190c33739d9c00f20/src/DotNetBridge/Bridge.cs#L314

**Comment by shmoradims** [comment]
Was not needed.
