### ISSUE TITLE
DotNetBridge: Refactor RunGraph to not use CmdParser

### ISSUE THREAD

**Issue by montebhoover** [Microsoft/NimbusML#84]
[`RunGraph`](https://github.com/Microsoft/NimbusML/blob/80ce48f0505eba1564dafd2dfd249905ee7b6143/src/DotNetBridge/RunGraph.cs#L88)
*Either* change the way we do native data interop with [`BytesToText`](https://github.com/Microsoft/NimbusML/blob/80ce48f0505eba1564dafd2dfd249905ee7b6143/src/DotNetBridge/Bridge.cs#L345) or continue using the BytesToText interop but implement parsing without ML.NET's [CmdParser](https://github.com/dotnet/machinelearning/blob/0c62e30b4d9eabb60322b2a3e75bc90e20007889/src/Microsoft.ML.Core/CommandLine/CmdParser.cs#L204).

**Comment by shmoradims** [comment]
Fixed by #77
