### ISSUE TITLE
Update ManifestGenerator (and other projects) to ML.NET v0.11

### ISSUE THREAD

**Issue by gyeongin** [microsoft/NimbusML#96]
Hi,
I want to make changes on the latest ML.NET (which is v0.11) and build NimbusML using my custom ML.NET NuGet that contains new entrypoints.
However, it seems like the ManifestGenerator project is outdated a bit (v0.7) so I cannot generate a new manifest.json from current ML.NET NuGet.
It would be great to update the ManifestGenerator (and other NimbusML projects like DotNetBridge if necessary) to support the latest v0.11 version.

**Comment by tauheedul** [comment]
The release candidate was released last week. Should this be updated to 1.0.0 preview or 1.0.0?

**Comment by justinormont** [comment]
See #100 for updating to 1.0.0 (yes, it's a lucky PR number)

**Comment by tauheedul** [comment]
Thanks @justinormont
